// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as TxnProcedure from "../txn_procedure";

export type TxnArgs = __Infer<typeof TxnProcedure.params>;
export type TxnResult = __Infer<typeof TxnProcedure.returnType>;

