// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DeleteRegisterReducer from "../delete_register_reducer";
import InsertRegisterReducer from "../insert_register_reducer";
import ListRegistersReducer from "../list_registers_reducer";

export type DeleteRegisterParams = __Infer<typeof DeleteRegisterReducer>;
export type InsertRegisterParams = __Infer<typeof InsertRegisterReducer>;
export type ListRegistersParams = __Infer<typeof ListRegistersReducer>;

