// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ListAppendProcedure from "../list_append_procedure";

export type ListAppendArgs = __Infer<typeof ListAppendProcedure.params>;
export type ListAppendResult = __Infer<typeof ListAppendProcedure.returnType>;

