// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Entry = __t.object("Entry", {
  account: __t.i32(),
  balance: __t.i32(),
});
export type Entry = __Infer<typeof Entry>;

export const Ledger = __t.object("Ledger", {
  account: __t.i32(),
  balance: __t.i32(),
});
export type Ledger = __Infer<typeof Ledger>;

export const LedgerView = __t.object("LedgerView", {});
export type LedgerView = __Infer<typeof LedgerView>;

export const Registers = __t.object("Registers", {
  k: __t.i32(),
  v: __t.i32(),
});
export type Registers = __Infer<typeof Registers>;

