// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Lists = __t.object("Lists", {
  key: __t.i32(),
  list: __t.option(__t.string()),
});
export type Lists = __Infer<typeof Lists>;

export const Mop = __t.object("Mop", {
  f: __t.string(),
  k: __t.i32(),
  v: __t.option(__t.option(__t.string())),
});
export type Mop = __Infer<typeof Mop>;

